networks:
    dev:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - backend
            - frontend
            - mongodb
        networks:
            - dev

    backend:
        build:
            context: ./backend
        networks:
            - dev

    frontend:
        build:
            context: ./frontend
        networks:
            - dev

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - dev
    mongo-express:
        image: mongo-express:latest
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
        depends_on:
            - mongodb
        networks:
            - dev
volumes:
    mongodb_data:
