networks:
    dev:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./ssl/certificate.crt:/etc/nginx/ssl/certificate.crt"
            - "./ssl/certificate.key:/etc/nginx/ssl/certificate.key"
        depends_on:
            - backend
            - frontend
            - mongodb
        networks:
            - dev

    backend:
        build:
            context: ./backend
        networks:
            - dev

    frontend:
        build:
            context: ./frontend
        networks:
            - dev

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - dev
volumes:
    mongodb_data:
        driver: local
